# -*- mode: ruby -*-
# vi: set ft=ruby :

# This Vagrantfile spins up a three Vault server nodes (with raft storage). Shamir-based seal. .

# Option to specify a Vault version.
#VAULT_VERSION = ENV['VAULT_VERSION'] || "1.9.0"
VAULT_VERSION = ENV['VAULT_VERSION'] || "$VAULT_VERSION"
VAULT_LICENSE = ENV['VAULT_LICENSE'] || "$VAULT_LICENSE"

if ENV['VAULT_VERSION'] == ''
	print "VAULT_VERSION environment variable not set, exiting ..."
        exit 1
elif ENV['VAULT_LICENSE'] == ''
	print "VAULT_LICENSE environment variable not set, exiting ..."
	exit 1
end
# VAULT_LICENSE = ENV['VAULT_LICENSE'] || "CHANGEME"
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "debian/stretch64"

# Vault server VMs                        
  config.vm.define "vault_alpha" do |vault_alpha|
      vault_alpha.vm.hostname = "vault-alpha"
      vault_alpha.vm.network "private_network", ip: "172.20.20.10"
      vault_alpha.vm.provision "shell", 
          path: "scripts/vault_alpha_setup.sh",
          env: {"VAULT_VERSION" => VAULT_VERSION,
                "VAULT_LICENSE" => VAULT_LICENSE,
                "VAULT_ADDR" => "http://0.0.0.0:8200"}

  end

  config.vm.define "vault_bravo" do |vault_bravo|
      vault_bravo.vm.hostname = "vault-bravo"
      vault_bravo.vm.network "private_network", ip: "172.20.20.11"
      vault_bravo.vm.provision "shell", 
          path: "scripts/vault_bravo_setup.sh",
          env: {"VAULT_VERSION" => VAULT_VERSION,
                "VAULT_LICENSE" => VAULT_LICENSE,
                "VAULT_ADDR" => "http://0.0.0.0:8200"}
 
  end

 config.vm.define "vault_charlie" do |vault_charlie|
      vault_charlie.vm.hostname = "vault-charlie"
      vault_charlie.vm.network "private_network", ip: "172.20.20.12"
      vault_charlie.vm.provision "shell",
          path: "scripts/vault_charlie_setup.sh",
          env: {"VAULT_VERSION" => VAULT_VERSION,
                "VAULT_LICENSE" => VAULT_LICENSE,
                "VAULT_ADDR" => "http://0.0.0.0:8200"}

  end

end 
